{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9ef59d01-bd62-4f8a-a64c-35df7922b8fd",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "Entry point for the ETL pipeline:\n",
    "- Chunked extraction\n",
    "- Parallel transform + write to parquet\n",
    "- Merge outputs\n",
    "- Benchmark vs. sequential\n",
    "\"\"\"\n",
    "\n",
    "import json\n",
    "from pathlib import Path\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "import config\n",
    "from etl import run_pipeline\n",
    "from benchmark import run_sequential_benchmark, compare_results\n",
    "\n",
    "\n",
    "def ensure_dirs():\n",
    "    for d in [config.DATA_DIR, config.OUTPUT_DIR, config.PARQUET_DIR, config.LOG_DIR]:\n",
    "        Path(d).mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "\n",
    "def plot_benchmark(par_metrics, seq_metrics, out_path: Path):\n",
    "    data = [\n",
    "        {\"mode\": \"Parallel\", \"time_s\": par_metrics[\"elapsed_seconds\"]},\n",
    "        {\"mode\": \"Sequential\", \"time_s\": seq_metrics[\"elapsed_seconds\"]}\n",
    "    ]\n",
    "    df = sns.load_dataset(\"tips\")  # dummy to guarantee seaborn load; we'll not use it\n",
    "    plt.figure(figsize=(6, 4))\n",
    "    modes = [d[\"mode\"] for d in data]\n",
    "    times = [d[\"time_s\"] for d in data]\n",
    "    sns.barplot(x=modes, y=times, palette=\"deep\")\n",
    "    plt.title(\"ETL Execution Time Comparison\")\n",
    "    plt.ylabel(\"Seconds\")\n",
    "    plt.xlabel(\"Mode\")\n",
    "    for i, t in enumerate(times):\n",
    "        plt.text(i, t, f\"{t:.2f}s\", ha=\"center\", va=\"bottom\")\n",
    "    out_path.parent.mkdir(parents=True, exist_ok=True)\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(out_path)\n",
    "    plt.close()\n",
    "\n",
    "\n",
    "def main():\n",
    "    ensure_dirs()\n",
    "\n",
    "    # Run parallel pipeline\n",
    "    par_metrics = run_pipeline(config)\n",
    "\n",
    "    # Run sequential benchmark for comparison\n",
    "    seq_metrics = run_sequential_benchmark(config.INPUT_FILE, config.CHUNK_SIZE, config)\n",
    "\n",
    "    # Compare\n",
    "    summary = compare_results(par_metrics, seq_metrics)\n",
    "\n",
    "    # Persist metrics\n",
    "    logs_json = {\n",
    "        \"parallel\": par_metrics,\n",
    "        \"sequential\": seq_metrics,\n",
    "        \"summary\": summary\n",
    "    }\n",
    "    log_file = Path(config.LOG_DIR) / \"metrics.json\"\n",
    "    log_file.write_text(json.dumps(logs_json, indent=2))\n",
    "    print(f\"Saved metrics to {log_file}\")\n",
    "\n",
    "    # Plot benchmark chart\n",
    "    plot_file = Path(config.OUTPUT_DIR) / \"benchmark_time_comparison.png\"\n",
    "    plot_benchmark(par_metrics, seq_metrics, plot_file)\n",
    "    print(f\"Saved benchmark chart to {plot_file}\")\n",
    "\n",
    "    # Optional CSV export of merged output\n",
    "    if config.WRITE_CSV_EXPORT and config.MERGED_PARQUET.exists():\n",
    "        import pandas as pd\n",
    "        df = pd.read_parquet(config.MERGED_PARQUET)\n",
    "        csv_path = Path(config.OUTPUT_DIR) / \"merged_output.csv\"\n",
    "        df.to_csv(csv_path, index=False)\n",
    "        print(f\"Saved CSV export to {csv_path}\")\n",
    "\n",
    "    # Console summary\n",
    "    print(\"\\n=== ETL Summary ===\")\n",
    "    for k, v in summary.items():\n",
    "        print(f\"{k}: {v}\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
