{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f43a9e5c-dc20-420e-9898-11129b89c3c1",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "def basic_clean(df: pd.DataFrame, required_cols=None, dtypes=None,\n",
    "                drop_duplicates=True, drop_na_rows=False) -> pd.DataFrame:\n",
    "    # Enforce required columns if provided\n",
    "    if required_cols:\n",
    "        missing = [c for c in required_cols if c not in df.columns]\n",
    "        if missing:\n",
    "            raise ValueError(f\"Missing required columns: {missing}\")\n",
    "\n",
    "    # Cast dtypes if provided\n",
    "    if dtypes:\n",
    "        for col, dtype in dtypes.items():\n",
    "            if col in df.columns:\n",
    "                df[col] = df[col].astype(dtype, errors=\"ignore\")\n",
    "\n",
    "    # Deduplicate\n",
    "    if drop_duplicates:\n",
    "        df = df.drop_duplicates()\n",
    "\n",
    "    # Drop NA rows if requested\n",
    "    if drop_na_rows:\n",
    "        df = df.dropna()\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "def feature_engineering(df: pd.DataFrame) -> pd.DataFrame:\n",
    "    # Example features (adapt to your domain)\n",
    "    # Create normalized numeric features\n",
    "    for col in df.select_dtypes(include=\"number\").columns:\n",
    "        max_val = df[col].max()\n",
    "        min_val = df[col].min()\n",
    "        if pd.notna(max_val) and pd.notna(min_val) and max_val != min_val:\n",
    "            df[f\"{col}_norm\"] = (df[col] - min_val) / (max_val - min_val)\n",
    "\n",
    "    # Example: timestamp to date, hour\n",
    "    for col in df.columns:\n",
    "        if \"time\" in col and \"event\" in col and df[col].dtype == \"object\":\n",
    "            ts = pd.to_datetime(df[col], errors=\"coerce\")\n",
    "            df[f\"{col}_date\"] = ts.dt.date\n",
    "            df[f\"{col}_hour\"] = ts.dt.hour\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "def transform_chunk(df: pd.DataFrame,\n",
    "                    required_cols=None,\n",
    "                    dtypes=None,\n",
    "                    enable_features=True,\n",
    "                    drop_duplicates=True,\n",
    "                    drop_na_rows=False) -> pd.DataFrame:\n",
    "    df = basic_clean(\n",
    "        df,\n",
    "        required_cols=required_cols,\n",
    "        dtypes=dtypes,\n",
    "        drop_duplicates=drop_duplicates,\n",
    "        drop_na_rows=drop_na_rows\n",
    "    )\n",
    "    if enable_features:\n",
    "        df = feature_engineering(df)\n",
    "    return df"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
